--------------------------------------------------------
--  File created - Wednesday-March-05-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XX_CUST_LIST
--------------------------------------------------------
  drop table "APPS"."XX_CUST_LIST" ;

  CREATE TABLE "APPS"."XX_CUST_LIST" 
   (	"CUST_LIST_ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"APPLICATION_ID" NUMBER, 
	"ASSESSMENT" VARCHAR2(2000 BYTE), 
	"USED" VARCHAR2(20 BYTE), 
	"R12_OBSOLETE" VARCHAR2(20 BYTE), 
	"R12_MIGRATE" VARCHAR2(20 BYTE), 
	"TEAM_OWNER" VARCHAR2(20 BYTE), 
	"CUSTOMISATION_NUMBER" NUMBER(38,0), 
	"PROCESS_NUMBER" VARCHAR2(30 BYTE), 
	"UAT_SCRIPT_NUMBER" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index XX_CUST_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."XX_CUST_LIST_PK" ON "APPS"."XX_CUST_LIST" ("CUST_LIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table XX_CUST_LIST
--------------------------------------------------------

  ALTER TABLE "APPS"."XX_CUST_LIST" ADD CONSTRAINT "XX_CUST_LIST_PK" PRIMARY KEY ("CUST_LIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
  ALTER TABLE "APPS"."XX_CUST_LIST" MODIFY ("CUST_LIST_ID" NOT NULL ENABLE);
